### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Willtrix** [Scezaquer/youtube-audio-downloader#1]
My command: python3 youtube-playlist-downloader.py
Error I got:
Traceback (most recent call last):
  File "/home/humanbeing/Public/YTDownloader/youtube-audio-downloader/youtube-playlist-downloader.py", line 12, in <module>
    with open("api_key.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'api_key.txt'

**Comment by Scezaquer** [comment]
Hi, I just updated the readme to be significantly more complete, which you might find helpful. Your problem is due to the fact that you need to create a api_key.txt file yourself, and put your youtube api key inside of it. More details available in the readme, in the "setup" section. Hope this helps!

**Comment by Willtrix** [comment]
The API seems very in-depth and useful. I'll take it for a spin soon and let you know what I think. Thank you so much!

**Comment by Willtrix** [comment]
Whooo! It works!
